

name: Run Smoke Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  smoke-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build and run Smoke tests
      run: mvn clean test -Dcucumber.filter.tags="@Hero"

    - name: Find latest report folder
      id: find_report
      run: |
        latest=$(ls -td test-reports/*/ 2>/dev/null | head -1)
        if [ -z "$latest" ]; then
          echo "No report folder found"
          echo "latest_report=" >> $GITHUB_OUTPUT
        else
          echo "Found report folder: $latest"
          echo "latest_report=$latest" >> $GITHUB_OUTPUT
        fi


    - name: Upload Cucumber HTML report
      if: ${{ steps.find_report.outputs.latest_report != '' }}
      uses: actions/upload-artifact@v4
      with:
        name: cucumber-smoke-report
        path: ${{ steps.find_report.outputs.latest_report }}
